export const CONFIGURATION_CREATE_REQUEST = "CONFIGURATION_CREATE_REQUEST";
export const CONFIGURATION_CREATE_SUCCESS = "CONFIGURATION_CREATE_SUCCESS";
export const CONFIGURATION_CREATE_FAIL = "CONFIGURATION_CREATE_FAIL";

export const CONFIGURATION_LIST_REQUEST = "CONFIGURATION_LIST_REQUEST";
export const CONFIGURATION_LIST_SUCCESS = "CONFIGURATION_LIST_SUCCESS";
export const CONFIGURATION_LIST_FAIL = "CONFIGURATION_LIST_FAIL";

export const CONFIGURATION_DELETE_REQUEST = "CONFIGURATION_DELETE_REQUEST";
export const CONFIGURATION_DELETE_SUCCESS = "CONFIGURATION_DELETE_SUCCESS";
export const CONFIGURATION_DELETE_FAIL = "CONFIGURATION_DELETE_FAIL";

export const CONSUMATOR_CREATE_REQUEST = "CONSUMATOR_CREATE_REQUEST";
export const CONSUMATOR_CREATE_SUCCESS = "CONSUMATOR_CREATE_SUCCESS";
export const CONSUMATOR_CREATE_FAIL = "CONSUMATOR_CREATE_FAIL";




export const CONSUMATOR_LIST_REQUEST = "CONSUMATOR_LIST_REQUEST";
export const CONSUMATOR_LIST_SUCCESS = "CONSUMATOR_LIST_SUCCESS";
export const CONSUMATOR_LIST_FAIL = "CONSUMATOR_LIST_FAIL";
